// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		int count = 0;
		int greater = 0;
		double lesser = 0;	
		double rand;
		while (count < n) {
			rand = Math.random();
			if (rand > 0.5) {greater = greater + 1;}
			else 			{lesser = lesser + 1;}
			count = count + 1;
		}
		System.out.println("> 0.5: " + greater + " times");
		System.out.println("<= 0.5: " + lesser + " times");
		if (lesser != 0) {
			System.out.println("Ratio: " + (greater / lesser));
		}
	}
}